### PR TITLE
java_keystore

### PR DESCRIPTION
**Pull request by isolovey**

### CODE REVIEW

**Comment by isolovey** [comment]
@mklassen I think this should be merged so that our `requirements.yml` refers to the correct commit of `community.general`. It is currently in use by the `wildfly` role.

**Comment by mklassen** [comment]
There are issues with the module as it can leave the system in an unknown state, e.g. delete and then fail to create. That should not be able to happen.

**Comment by isolovey** [comment]
We discussed using [`community.crypto.openssl_pkcs12`](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_pkcs12_module.html) for generating the keystore and truststore, due to it using the more general OpenSSL library instead of relying on Java keystore tools.

The truststore created using this module (via OpenSSL) does not work in `dcm4chee-arc-light` (it finds no certificates and treats it as empty). Java 8 supports PKCS12 trust stores [with customizations](https://stackoverflow.com/a/42959499/1168152) that are [not supported by OpenSSL](https://github.com/openssl/openssl/issues/6684), and it doesn't look like they will be in the near future.

I think we should stick to `keytool`-based `java_keystore` module for now. The issues with leaving the system in an unknown state can be partially addressed by using [`AnsibleModule.tmpdir`](https://github.com/ansible/ansible/blob/2cbfd1e350cbe1ca195d33306b5a9628667ddda8/lib/ansible/module_utils/basic.py#L5420) and `AnsibleModule.atomic_move`.

**Comment by mklassen** [comment]
Moving to version 3 which includes a major rewrite of `plugins/modules/system/java_keystore.py`, so these changes should be moved to new version. Upstream already supports `type` as `keystore_type` in version 3.3, so the modification may all be redundant.

**Pull request closed without merging**
